2023-03-28 22:40:32 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:285:19)
    at DataSource.close (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:302:21)
    at DataSource.initialize (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:260:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CustomerService.initRepository (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/config/base.service.ts:12:24)
2023-03-28 22:40:32 error: uncaughtException: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'is_name_usage_on_website_granted'; check that column/key exists
QueryFailedError: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'is_name_usage_on_website_granted'; check that column/key exists
    at Query.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:88:28)
2023-03-28 22:41:29 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:285:19)
    at DataSource.close (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:302:21)
    at DataSource.initialize (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:260:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at UserService.initRepository (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/config/base.service.ts:12:24)
2023-03-28 22:41:29 error: uncaughtException: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'is_name_usage_on_social_media_granted'; check that column/key exists
QueryFailedError: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'is_name_usage_on_social_media_granted'; check that column/key exists
    at Query.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:88:28)
2023-03-28 22:42:44 error: uncaughtException: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'is_content_usage_on_website_granted'; check that column/key exists
QueryFailedError: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'is_content_usage_on_website_granted'; check that column/key exists
    at Query.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:88:28)
2023-03-28 22:42:44 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:285:19)
    at DataSource.close (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:302:21)
    at DataSource.initialize (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:260:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at UserService.initRepository (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/config/base.service.ts:12:24)
2023-03-28 22:44:21 error: uncaughtException: Cannot enqueue Query after invoking quit.
QueryFailedError: Cannot enqueue Query after invoking quit.
    at Query.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Protocol.js:236:14
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
2023-03-28 22:44:21 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:285:19)
    at DataSource.close (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:302:21)
    at DataSource.initialize (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:260:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CustomerService.initRepository (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/config/base.service.ts:12:24)
2023-03-28 22:44:26 error: uncaughtException: Cannot enqueue Query after invoking quit.
QueryFailedError: Cannot enqueue Query after invoking quit.
    at Query.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /home/rabindranath/Documents/Backend/yt-node-api-ts-oop/node_modules/mysql/lib/protocol/Protocol.js:236:14
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
2023-03-28 22:44:26 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:285:19)
    at DataSource.close (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:302:21)
    at DataSource.initialize (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/data-source/DataSource.ts:260:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CustomerService.initRepository (/home/rabindranath/Documents/Backend/yt-node-api-ts-oop/src/config/base.service.ts:12:24)
